security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Définir plusieurs fournisseurs pour gérer les différentes entités d'utilisateurs
        chain_provider:
            chain:
                providers: [app_user_provider, app_student_provider]
        
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
                
        app_student_provider:
            entity:
                class: App\Entity\Student
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            lazy: true
            provider: chain_provider  # Utilisez le fournisseur en chaîne
            custom_authenticator: App\Security\TwoFactorAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/verify-code, roles: PUBLIC_ACCESS }
        - { path: ^/resend-code, roles: PUBLIC_ACCESS }
        - { path: ^/field-manager/new, roles: PUBLIC_ACCESS }
        - { path: ^/student, roles: ROLE_STUDENT }
        - { path: ^/admin/new, roles: PUBLIC_ACCESS }
        - { path: ^/university/new, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }