parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/profiles'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite du FileUploader
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%uploads_directory%'
    
    # Configuration de l'écouteur de login
    App\EventListener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'
            $verificationCodeService: '@App\Service\VerificationCodeService'
    # Configuration de l'écouteur de logout
    App\EventListener\LogoutListener:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LogoutEvent }